interface Item {
  id: number;
  name: string;
  weight: number;
  itemType: "OTHER" | "REDEEMABLE" | "EQUIPABLE" | "CONSUMABLE";
  maxSupply: number;
  attackImpact?: number;
  defenseImpact?: number;
  probabilityImpact?: number;
  description: string;
  image: string;
}

const URL_PREFIX =
  "https://raw.githubusercontent.com/alma-labs/unimon-lists/refs/heads/main/assets/items";

export const items: Item[] = [
  {
    id: 0,
    name: "Unimon Energy",
    weight: 0,
    itemType: "OTHER",
    maxSupply: 0,
    description:
      "Pure energy essence that evolves your Unimon and can revive fainted Unimon (up to 2x).",
    image: `${URL_PREFIX}/0.png`,
  },
  {
    id: 1,
    name: "Unikey",
    weight: 0,
    itemType: "OTHER",
    maxSupply: 0,
    description:
      "A special key that unlocks Gachas to get helpful equipment and items. Redeemed in spawn room.",
    image: `${URL_PREFIX}/1.png`,
  },
  {
    id: 2,
    name: "Mint Coupon",
    weight: 0,
    itemType: "OTHER",
    maxSupply: 0,
    description:
      "A valuable coupon that allows you to mint new Unimon at 50% off.",
    image: `${URL_PREFIX}/2.png`,
  },
  {
    id: 3,
    name: "Uniball (UNI)",
    weight: 50,
    itemType: "REDEEMABLE",
    maxSupply: 69,
    description:
      "A special ball containing UNI tokens that can be redeemed for rewards.",
    image: `${URL_PREFIX}/3.png`,
  },
  {
    id: 4,
    name: "Pink Pouch (UNI)",
    weight: 10,
    itemType: "REDEEMABLE",
    maxSupply: 11,
    description:
      "A pink pouch filled with UNI tokens that can be redeemed for rewards.",
    image: `${URL_PREFIX}/4.png`,
  },
  {
    id: 5,
    name: "Uni Cartridge (UNI)",
    weight: 10,
    itemType: "REDEEMABLE",
    maxSupply: 11,
    description:
      "A cartridge containing UNI tokens that can be extracted and used.",
    image: `${URL_PREFIX}/5.png`,
  },
  {
    id: 6,
    name: "Trainer Badge (UNI)",
    weight: 10,
    itemType: "REDEEMABLE",
    maxSupply: 11,
    description:
      "A trainer badge containing UNI tokens that can be redeemed at the general store.",
    image: `${URL_PREFIX}/6.png`,
  },
  {
    id: 7,
    name: "L2 Goodiebag (WETH)",
    weight: 10,
    itemType: "REDEEMABLE",
    maxSupply: 11,
    description: "A goodie bag from Layer 2 containing WETH rewards.",
    image: `${URL_PREFIX}/7.png`,
  },
  {
    id: 8,
    name: "Unisocks (WETH)",
    weight: 3,
    itemType: "REDEEMABLE",
    maxSupply: 3,
    description: "Rare Uniswap socks that can be redeemed for WETH.",
    image: `${URL_PREFIX}/8.png`,
  },
  {
    id: 9,
    name: "Swapium Short Sword",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 0,
    probabilityImpact: 0,
    description: "A basic sword made from Swapium that increases attack power.",
    image: `${URL_PREFIX}/9.png`,
  },
  {
    id: 10,
    name: "Swapium Buckler",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 1,
    probabilityImpact: 0,
    description:
      "A small shield made from Swapium that provides basic protection.",
    image: `${URL_PREFIX}/10.png`,
  },
  {
    id: 11,
    name: "Swapium Helm",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 0,
    description:
      "A helmet made from Swapium that provides balanced attack and defense.",
    image: `${URL_PREFIX}/11.png`,
  },
  {
    id: 12,
    name: "L2 Longsword",
    weight: 500,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 2,
    defenseImpact: 0,
    probabilityImpact: 0,
    description:
      "A powerful longsword forged on Layer 2 with enhanced attack capabilities.",
    image: `${URL_PREFIX}/12.png`,
  },
  {
    id: 13,
    name: "L2 Shield",
    weight: 500,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 2,
    probabilityImpact: 0,
    description:
      "A sturdy shield crafted on Layer 2 that provides excellent defense.",
    image: `${URL_PREFIX}/13.png`,
  },
  {
    id: 14,
    name: "L2 Medium Helm",
    weight: 500,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 2,
    probabilityImpact: 0,
    description:
      "A medium-weight helmet from Layer 2 with good defensive properties.",
    image: `${URL_PREFIX}/14.png`,
  },
  {
    id: 15,
    name: "Uni Scimmy",
    weight: 50,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 3,
    defenseImpact: -1,
    probabilityImpact: 0,
    description: "A curved sword with high attack power but reduced defense.",
    image: `${URL_PREFIX}/15.png`,
  },
  {
    id: 16,
    name: "Uni Godshield",
    weight: 50,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: -1,
    defenseImpact: 3,
    probabilityImpact: 0,
    description:
      "A divine shield with exceptional defense but slightly reduced attack.",
    image: `${URL_PREFIX}/16.png`,
  },
  {
    id: 17,
    name: "Uni Full Helm",
    weight: 25,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 3,
    probabilityImpact: 0,
    description:
      "A full coverage helmet providing excellent protection and some attack boost.",
    image: `${URL_PREFIX}/17.png`,
  },
  {
    id: 18,
    name: "Leveraged Blade",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 5,
    defenseImpact: 0,
    probabilityImpact: -10,
    description:
      "A high-risk, high-reward blade with massive attack power but reduced luck.",
    image: `${URL_PREFIX}/18.png`,
  },
  {
    id: 19,
    name: "Leveraged Defender",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 5,
    probabilityImpact: -10,
    description:
      "A high-risk, high-reward defensive shield with high protection but comes with increased risk.",
    image: `${URL_PREFIX}/19.png`,
  },
  {
    id: 20,
    name: "Leveraged Guard",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 3,
    defenseImpact: 3,
    probabilityImpact: -10,
    description:
      "High-risk, high-reward protective gear with good stats but negative probability impact.",
    image: `${URL_PREFIX}/20.png`,
  },
  {
    id: 21,
    name: "Catex Ears",
    weight: 250,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 0,
    description:
      "Adorable cat ears that provide modest attack and defense bonuses.",
    image: `${URL_PREFIX}/21.png`,
  },
  {
    id: 22,
    name: "Trimmed Rune Helmet",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 2,
    probabilityImpact: -5,
    description: "Free armor trimming, you in?",
    image: `${URL_PREFIX}/22.png`,
  },
  {
    id: 23,
    name: "Straw Hat",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 1,
    probabilityImpact: 0,
    description:
      "A simple straw hat that provides basic protection from the elements.",
    image: `${URL_PREFIX}/23.png`,
  },
  {
    id: 24,
    name: "Mog Glasses",
    weight: 500,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 3,
    description:
      "Stylish glasses that improve vision and increase luck in battles.",
    image: `${URL_PREFIX}/24.png`,
  },
  {
    id: 25,
    name: "Permenant Loss",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: -100,
    description:
      "A cursed item that binds your own Unimon's legs, making them unable to move. Guaranteed loss.",
    image: `${URL_PREFIX}/25.png`,
  },
  {
    id: 26,
    name: "Uni Saddle",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 1,
    probabilityImpact: 0,
    description:
      "A comfortable saddle that provides stability and minor defensive benefits.",
    image: `${URL_PREFIX}/26.png`,
  },
  {
    id: 27,
    name: "Fedora",
    weight: 1000,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 0,
    probabilityImpact: 1,
    description:
      "A classy fedora that makes you look distinguished and slightly luckier. Said to be worn by the king of Reddit.",
    image: `${URL_PREFIX}/27.png`,
  },
  {
    id: 28,
    name: "Pink Chain",
    weight: 100,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 2,
    probabilityImpact: 5,
    description:
      "A pink chain that provides protection and brings good fortune.",
    image: `${URL_PREFIX}/28.png`,
  },
  {
    id: 29,
    name: "Horse Head",
    weight: 500,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 3,
    description: "A mysterious horse head mask that increases your luck.",
    image: `${URL_PREFIX}/29.png`,
  },
  {
    id: 30,
    name: "Unicloak",
    weight: 10,
    itemType: "EQUIPABLE",
    maxSupply: 0,
    attackImpact: 2,
    defenseImpact: 2,
    probabilityImpact: 2,
    description:
      "A magical cloak that provides balanced improvements to all abilities.",
    image: `${URL_PREFIX}/30.png`,
  },
  {
    id: 31,
    name: "Green Candle",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 11,
    description:
      "A green candle that burns with magical energy, boosting your abilities & luck.",
    image: `${URL_PREFIX}/31.png`,
  },
  {
    id: 32,
    name: "Uni Energy Drink",
    weight: 50,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 2,
    defenseImpact: 2,
    probabilityImpact: 22,
    description:
      "An energizing drink that boosts all stats and brings excellent luck.",
    image: `${URL_PREFIX}/32.png`,
  },
  {
    id: 33,
    name: "Broken Horn",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: -5,
    description: "A broken unicorn horn that brings slight misfortune.",
    image: `${URL_PREFIX}/33.png`,
  },
  {
    id: 34,
    name: "Common Horn",
    weight: 750,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 1,
    description: "A basic unicorn horn that provides a small luck boost.",
    image: `${URL_PREFIX}/34.png`,
  },
  {
    id: 35,
    name: "Uncommon Horn",
    weight: 500,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 5,
    description:
      "An uncommon unicorn horn with moderate luck-enhancing properties.",
    image: `${URL_PREFIX}/35.png`,
  },
  {
    id: 36,
    name: "Epic Horn",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 10,
    description:
      "An epic unicorn horn that significantly improves your fortune.",
    image: `${URL_PREFIX}/36.png`,
  },
  {
    id: 37,
    name: "Mythic Horn",
    weight: 75,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 15,
    description: "A mythic unicorn horn with powerful luck-enhancing magic.",
    image: `${URL_PREFIX}/37.png`,
  },
  {
    id: 38,
    name: "Divine Horn",
    weight: 25,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 20,
    description:
      "A divine unicorn horn blessed with extraordinary luck powers.",
    image: `${URL_PREFIX}/38.png`,
  },
  {
    id: 39,
    name: "Ultimate Horn",
    weight: 10,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 25,
    description:
      "The ultimate unicorn horn with unmatched luck-granting abilities.",
    image: `${URL_PREFIX}/39.png`,
  },
  {
    id: 40,
    name: "Ginny Horn",
    weight: 3,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 50,
    description:
      "A legendary horn from Talladega 500. If you don't know, don't ask.",
    image: `${URL_PREFIX}/40.png`,
  },
  {
    id: 41,
    name: "Broken Horseshoe",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: -5,
    description: "A broken horseshoe that brings bad luck instead of good.",
    image: `${URL_PREFIX}/41.png`,
  },
  {
    id: 42,
    name: "Lucky Horseshoe",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 11,
    description:
      "A lucky horseshoe that brings good fortune and positive energy.",
    image: `${URL_PREFIX}/42.png`,
  },
  {
    id: 43,
    name: "Uni v4 Hook",
    weight: 4,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 44,
    description:
      "A special hook from Uniswap v4 that greatly enhances your luck.",
    image: `${URL_PREFIX}/43.png`,
  },
  {
    id: 44,
    name: "Rainbow Horseshoe",
    weight: 10,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 0,
    probabilityImpact: 33,
    description:
      "A colorful horseshoe that brings rainbow luck and positive vibes.",
    image: `${URL_PREFIX}/44.png`,
  },
  {
    id: 45,
    name: "Strange Pink Powder",
    weight: 50,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 4,
    defenseImpact: 0,
    probabilityImpact: -25,
    description:
      "A mysterious pink powder that boosts attack but brings bad luck.",
    image: `${URL_PREFIX}/45.png`,
  },
  {
    id: 46,
    name: "Unicorn Tranquilizer",
    weight: 50,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 4,
    probabilityImpact: -25,
    description:
      "A tranquilizer that enhances defense but clouds judgment & reduces luck.",
    image: `${URL_PREFIX}/46.png`,
  },
  {
    id: 47,
    name: "Cerulean City Cig",
    weight: 3,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 10,
    defenseImpact: 10,
    probabilityImpact: 100,
    description: "Imagine ripping one of these in Uniland. Guaranteed win.",
    image: `${URL_PREFIX}/47.png`,
  },
  {
    id: 48,
    name: "Unicig",
    weight: 100,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 3,
    defenseImpact: 3,
    probabilityImpact: 3,
    description:
      "A balanced ciggy that provides modest improvements to all stats.",
    image: `${URL_PREFIX}/48.png`,
  },
  {
    id: 49,
    name: "Uninana",
    weight: 1000,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 1,
    description:
      "A nutritious fruit that provides small boosts to all abilities & luck.",
    image: `${URL_PREFIX}/49.png`,
  },
  {
    id: 50,
    name: "Uniberry",
    weight: 1000,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 2,
    defenseImpact: 2,
    probabilityImpact: 2,
    description: "A magical berry that enhances all stats & luck.",
    image: `${URL_PREFIX}/50.png`,
  },
  {
    id: 51,
    name: "Uniswap Growth Potion",
    weight: 500,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 10,
    description: "A potion that promotes growth and brings significant luck.",
    image: `${URL_PREFIX}/51.png`,
  },
  {
    id: 52,
    name: "Uniswap Labs Elixir",
    weight: 500,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 0,
    probabilityImpact: 10,
    description: "An elixir from Uniswap Labs that boosts attack and luck.",
    image: `${URL_PREFIX}/52.png`,
  },
  {
    id: 53,
    name: "Uni Foundation Flask",
    weight: 500,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 0,
    defenseImpact: 1,
    probabilityImpact: 10,
    description:
      "A flask from the Uni Foundation that enhances defense and fortune.",
    image: `${URL_PREFIX}/53.png`,
  },
  {
    id: 54,
    name: "UNI Delegate Brew",
    weight: 500,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 1,
    defenseImpact: 1,
    probabilityImpact: 5,
    description:
      "A special brew for UNI delegates that provides balanced stat improvements & luck.",
    image: `${URL_PREFIX}/54.png`,
  },
  {
    id: 55,
    name: "Pink Pill",
    weight: 50,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: -4,
    defenseImpact: -4,
    probabilityImpact: 69,
    description:
      "A controversial pill that weakens you but brings extraordinary luck.",
    image: `${URL_PREFIX}/55.png`,
  },
  {
    id: 56,
    name: "Liquidity Potion",
    weight: 10,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 5,
    defenseImpact: -5,
    probabilityImpact: 0,
    description: "A potion that greatly increases attack but reduces defense.",
    image: `${URL_PREFIX}/56.png`,
  },
  {
    id: 57,
    name: "Hayden Adams' Glasses",
    weight: 10,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: -5,
    defenseImpact: 5,
    probabilityImpact: 0,
    description:
      "The founder's glasses that reduce attack but significantly boost defense.",
    image: `${URL_PREFIX}/57.png`,
  },
  {
    id: 58,
    name: "Honeypot",
    weight: 50,
    itemType: "CONSUMABLE",
    maxSupply: 0,
    attackImpact: 10,
    defenseImpact: 10,
    probabilityImpact: -100,
    description:
      "A dangerous honeypot that greatly boosts stats but guarantees a loss. Don't fall for it.",
    image: `${URL_PREFIX}/58.png`,
  },
];
